### ISSUE TITLE
Product recommendations

### ISSUE THREAD

**Issue by lazreg87** [kvassAI/order-widget#13]
Default to showing the top 5 products sold when first opening up the widget, and then 1 or 2 lines of highlighted product recommendations based on your current search

**Comment by lazreg87** [comment]
We have three different types of recommendations that we want to display in the widget:

1. personal product recommendation, based on previous purchases
2. similar product recommendations, based on one product
3. complementary product recommendations, based on your basket of products

@pedropregueiro & @datascienceit, please correct me if I'm wrong

**Comment by lazreg87** [comment]
1. personal recommendations
![8ea8ab6fd90f4b52ba78115fe70dada7](https://user-images.githubusercontent.com/6033889/41585148-79b87542-73a9-11e8-9ba8-7c052c1c73ea.png)

2. similar recommendations
![d4139cc9e048390865fd1dbdd24d9ea0c](https://user-images.githubusercontent.com/6033889/41586251-9bb1d9f6-73ac-11e8-86bf-d5a9f854b70c.png)

3. complementary recommendations
![dd859eb9bac3cf118342d4ffdf8540f96](https://user-images.githubusercontent.com/6033889/41586264-a9242e0e-73ac-11e8-974e-7a55c7e1d30e.png)

**Comment by pedropregueiro** [comment]
I think the complementary items, aka. "people who bought X also bought this:" should be on the product page as well.

for the checkout, we could have bundles, but we don't have it today, correct @datascienceit ?

**Comment by lazreg87** [comment]
@pedro, so there would be one recommendation feed with both types?

**Comment by pedropregueiro** [comment]
for "1. personal product recommendation, based on previous purchases", if you send a random user id "123", you'll get popular items, instead of user recommendations

**Comment by lazreg87** [comment]
Will implement https://github.com/kvassAI/javascript-sdk/issues/19 first before moving to this issue

**Comment by lazreg87** [comment]
Training two models for our ecommerce demo company: content_similarity_graph and  frequent_items_recommender
