### ISSUE TITLE
Issue with address being stored

### ISSUE THREAD

**Issue by pedropregueiro** [kvassAI/order-widget#69]
I used the address: "Tromsøgata 19, Oslo", but in the dashboard's Order data, I got the below:
<img width="696" alt="screenshot 2018-06-26 09 38 35" src="https://user-images.githubusercontent.com/314617/41899677-fa9178b4-7924-11e8-8659-8bea66e5b820.png">

Not sure if widget related or API

**Comment by tigo0** [comment]
This is what the order widget is sending: 
![image](https://user-images.githubusercontent.com/6010279/41961669-beb4573a-79fb-11e8-9cfa-61cebabad675.png)
Maybe the *building* is not properly handled?

**Comment by NicolasBonduel** [comment]
Can it be a dashboard issue?

**Comment by tigo0** [comment]
Its an issue on the dashboard. We do not take **building** into consideration. Closing here.
