### ISSUE TITLE
Use "Powered by"

### ISSUE THREAD

**Issue by pedropregueiro** [kvassAI/order-widget#71]
On the bottm right of the screen, use "Powered **b**y"

**Comment by tigo0** [comment]
It has **Powered By ...** on the bottom right on the widget.
![image](https://user-images.githubusercontent.com/6010279/41972810-acbb64ae-7a1b-11e8-9e25-3490af9b3f02.png)

**Comment by pedropregueiro** [comment]
yeah, but can you change it to "Powered by" pls. not my request :)

**Comment by tigo0** [comment]
Oh you mean the uppercase thingy, sorry didn't realize :D
